print("Welcome to Tip Calculator")
total_bill = input("What was the total Bill ? ₹")
floattotal_bill = float(total_bill)
tip = input("How much tip do You want to Give ?")
inttip = int(tip)
percent_tip = floattotal_bill * (inttip / 100)
grand_total_bill = floattotal_bill + float(percent_tip)
floatgrand_total_bill = float(grand_total_bill)
split_bill = input("How many people to split the bill ?")
intsplit_bill = int(split_bill)
each_person_pay = floatgrand_total_bill / intsplit_bill
# roundpay = round(each_person_pay, 2)
# roundpay = "{:.2f}".format(each_person_pay)
print(f"Each Person Should Pay: ₹{round(each_person_pay,2)}")
